### PR TITLE
Make it so we can use prefix "nigga please"

### PR DESCRIPTION
**Pull request by YourAverageBlackGuy**

### CODE REVIEW

**Comment by uwx** [comment]
you realize naam uploads the builds manually right

**Comment by YourAverageBlackGuy** [comment]
yea

**Comment by YourAverageBlackGuy** [comment]
ill wait till tomorrow

**Comment by li223** [comment]
Can we change it to a sensible number like 15 or 20. I can't allow it to be 13. It's too much man.

**Comment by moonPtr** [comment]
I agree, 20 is good

**Pull request merged**
